package Track;

import GUIInterface.AppGUIModule;
import TrackConstruction.*;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author grhen
 */

public class TrackGUI extends javax.swing.JFrame implements AppGUIModule {

    //Adding Track Components
    Track trackList;
    DefaultTableModel model;
    DefaultTableModel switches;
    DefaultTableModel beacons;
    DefaultTableModel mainInputs;
    public Timer timer;
    int GREENDISP = 0;


    /**
     * Creates new form TrackGUI
     */
    public TrackGUI(Track trackL) {
        initComponents();
        this.trackList = trackL;
    }

    /**
     * Creating returning track -- method to be called by simulation environment
     */
    public Track returnTrack() {
        return trackList;
    }

    /**
     * update Tracklist -- method to be called by simulation environment
     */

    public void latch(Object myObject) {

        Track givenSystem = null;
        try {
            givenSystem = (Track) myObject;
        } catch (Exception e) {
            e.printStackTrace();
        }

        trackList = (Track) myObject;
    }

    public void update() {
    } //automatically updates no need to do this

    @Override
    public Object getJFrame() {
        return this;
    }

    public void draw() {

    } // for interface

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Menu = new javax.swing.JPanel();
        loadTrack = new javax.swing.JButton();
        viewTrack = new javax.swing.JButton();
        viewBlock = new javax.swing.JButton();
        tickets = new javax.swing.JButton();
        signal = new javax.swing.JButton();
        failures = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        panel_center = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TemperaturePane = new javax.swing.JTextPane();
        jTextField12 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        greenTrack = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        updateTest = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BlockNumTest = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lineTest = new javax.swing.JTextField();
        occupiedTest = new javax.swing.JTextField();
        failStatusTest = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        authorityTest = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        speedTest = new javax.swing.JTextField();
        switchTest = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        passengerTest = new javax.swing.JTextField();
        jTestBlue = new javax.swing.JButton();
        lengthTraveled = new javax.swing.JTextField();

        jScrollPane9.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadTrack.setText("Input Track");
        loadTrack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadTrack(evt);
            }
        });

        viewTrack.setText("View Track");
        viewTrack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTrack(evt);
            }
        });

        viewBlock.setText("View Block");
        viewBlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBlock(evt);
            }
        });

        tickets.setText("Ticket Sales");
        tickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tickets(evt);
            }
        });


        signal.setText("Switches/Signals/Beacons");
        signal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signal(evt);
            }
        });

        failures.setText("Failures");
        failures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                failures(evt);
            }
        });

        jButton9.setText("TEST GUI");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
                MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(viewTrack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(viewBlock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tickets, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(signal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(loadTrack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(failures, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
                MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(loadTrack)
                                .addGap(33, 33, 33)
                                .addComponent(viewTrack)
                                .addGap(31, 31, 31)
                                .addComponent(viewBlock)
                                .addGap(29, 29, 29)
                                .addComponent(tickets)
                                .addGap(18, 18, 18)
                                .addComponent(signal)
                                .addGap(27, 27, 27)
                                .addComponent(failures)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_center.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Input Track");

        jTextField1.setText("Input File");

        Submit.setText("Submit");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SubmitMouseReleased(evt);
            }
        });


        jLabel5.setText("Input File");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(524, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addGap(63, 63, 63)
                                .addComponent(Submit)
                                .addGap(0, 475, Short.MAX_VALUE))
        );

        panel_center.add(jPanel1, "card2");

        jLabel1.setText("Track Layout");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Block Number", "Line", "Section", "Direction (to)", "Current Direction", "Infrastructure", "Occupied", "Status", "Length", "Grade", "SpeedLimit MPH", "Elevation", "Cummulative Elevation"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane4.setViewportView(TemperaturePane);

        jTextField12.setText("Update Temp");

        jButton12.setText("Submit");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jLabel24.setText("Update Temp:");

        greenTrack.setText("greenLine");
        greenTrack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                greenTrackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1)
                                .addGap(102, 102, 102)
                                .addComponent(greenTrack)
                                .addGap(152, 152, 152)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel1)
                                                                .addComponent(greenTrack))
                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(17, 17, 17))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton12)
                                                        .addComponent(jLabel24))
                                                .addGap(18, 18, 18)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                                .addContainerGap())
        );

        panel_center.add(jPanel2, "card3");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Line", "Block Number", "Station Name", "Ticket Sales", "People Leave"
                }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(54, Short.MAX_VALUE))
        );

        panel_center.add(jPanel4, "card5");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextField2.setText("Input Block Number");

        jButton5.setText("Okay");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });

        jLabel6.setText("Input Block Number:");

        jTextField3.setText("Input Line");

        jLabel7.setText("Input Line:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(272, 272, 272)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(463, 463, 463)
                                                                .addComponent(jLabel6)
                                                                .addGap(66, 66, 66))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel7)
                                                                .addGap(88, 88, 88)))
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(35, 35, 35)
                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel6))
                                                                .addGap(16, 16, 16)
                                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(35, 35, 35)
                                                                .addComponent(jButton5)))))
                                .addContainerGap(298, Short.MAX_VALUE))
        );

        panel_center.add(jPanel3, "card4");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Line", "Block", "Switches", "Switch Status"
                }
        ));
        jScrollPane5.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "Line", "Block ", "Occupied", "Authority", "Commanded Speed MPH"
                }
        ));
        jScrollPane6.setViewportView(jTable4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Line", "Block", "Station", "Beacon"
                }
        ));
        jScrollPane7.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(39, 39, 39))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(88, Short.MAX_VALUE))
        );

        panel_center.add(jPanel5, "card6");

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Line", "Block", "Failure Status"
                }
        ));
        jScrollPane8.setViewportView(jTable6);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(38, Short.MAX_VALUE))
        );

        panel_center.add(jPanel6, "card7");

        jLabel8.setText("TESTING UI");

        jLabel9.setText("CHANGE BLOCK INFO / SET FAILURES:");

        jButton10.setText("LOAD TEST TRACK (RED / GREEN)");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        updateTest.setText("Update");
        updateTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateTestMouseClicked(evt);
            }
        });


        jLabel11.setText("Authority / Commanded Speed Wayside");

        jLabel12.setText("Track Circuit Switch");

        jLabel14.setText("Throughput at Station");

        BlockNumTest.setText("Block Number");

        jLabel15.setText("Block Number:");

        jLabel16.setText("Line: (Red / Green / Blue)");

        jLabel17.setText("Occupied 1 - yes, 0 - no:");

        lineTest.setText("Line");

        occupiedTest.setText("Occupied");

        failStatusTest.setText("Failure Status");

        jLabel18.setText("Failure Status:");

        jLabel19.setText("0 - none, 1 - broken rail, 2 - power failurel, 3 - circuit failure");

        authorityTest.setText("Authority");

        jLabel20.setText("Authority:");

        jLabel21.setText("Commanded Speed:");

        speedTest.setText("Speed");

        switchTest.setText("Change Switch");

        jLabel22.setText("Switch Change:");

        jLabel23.setText("Passengers Leave Train:");

        passengerTest.setText("-1");

        jTestBlue.setText("LOAD TEST TRACK (BLUE)");
        jTestBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTestBlueMouseClicked(evt);
            }
        });

        lengthTraveled.setText("Length Traveled");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel17)
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel16))
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(failStatusTest, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                        .addComponent(BlockNumTest)
                                                        .addComponent(lineTest)
                                                        .addComponent(occupiedTest))))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(62, 62, 62)
                                                                .addComponent(jTestBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(authorityTest, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                                .addComponent(jLabel21)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(speedTest)))
                                                                .addGap(47, 47, 47)
                                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(switchTest, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addGap(111, 111, 111)
                                                                .addComponent(lengthTraveled, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel14))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(passengerTest, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(72, 72, 72))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addComponent(updateTest))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jButton10)))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel10))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jTestBlue)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BlockNumTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)
                                        .addComponent(authorityTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20)
                                        .addComponent(switchTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23)
                                        .addComponent(passengerTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lineTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel21)
                                                .addComponent(speedTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(occupiedTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lengthTraveled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(failStatusTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(updateTest)
                                .addGap(257, 257, 257))
        );

        panel_center.add(jPanel7, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_center, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_center, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>



    private void loadTrack(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
    }

    //This is to view the Track
    private void viewTrack(java.awt.event.MouseEvent evt) {
        //Make VIEW TRACK VISIBLE
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);

        //Here make the Track Heater status shown
        if(trackList != null) {
            //Load in Temperature
            TemperaturePane.setText("Environmental Temperature:" + trackList.getEnvironmentalTemperature() + "\n Track Heater Status: " + trackList.getTrackHeaterStatus());
            //Load in the Track
               refreshRedGreenTrack();


        }
    }

    private void updateRedGreenTrack(){
        ArrayList<TrackElement> tempBlocks = trackList.getBlocks();
        if (GREENDISP == 1)
            tempBlocks = trackList.getGreenLine();
        model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        //Display Track Information
        for(int i=0; i<tempBlocks.size(); i++)
            model.addRow(new Object[] {tempBlocks.get(i).getBlockNum(),tempBlocks.get(i).getLine(),tempBlocks.get(i).getSection(), tempBlocks.get(i).getCurrentDirection(),tempBlocks.get(i).getDirectionString(),tempBlocks.get(i).getInfrastructure(), tempBlocks.get(i).getOccupied(), tempBlocks.get(i).getFailureStatus(), tempBlocks.get(i).getLength(), tempBlocks.get(i).getGrade(), tempBlocks.get(i).getSpeedLimit(), tempBlocks.get(i).getElevation(), tempBlocks.get(i).getCumulativeElevation() });
    }
    /*refreshing screen */
    public void refreshRedGreenTrack() {
        timer = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateRedGreenTrack();
            }
        });

        timer.setRepeats(true);
        // Aprox. 60 FPS
        timer.setDelay(17);
        timer.start();
    }

    /*This is button for inputing Track Data */
    private void SubmitMouseReleased(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        String filepath = jTextField1.getText().trim();

        Track test = new Track();
        if(test.validFile(filepath)){ // C:\Users\grhen\OneDrive\Documents\Test.csv"
            JOptionPane.showMessageDialog(null, "Correct FilePath: " + filepath);


            if(test.importTrack(filepath)) {
                trackList = test;
                JOptionPane.showMessageDialog(null, "Track Successfully Loaded" + filepath);
            }
            else
                JOptionPane.showMessageDialog(null, "ERROR: Track not loaded" + filepath);
        }
        else{
            JOptionPane.showMessageDialog(null, "Not Valid Filepath " + filepath);
        }
    }


    private void viewBlock(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
    }

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        String num = jTextField2.getText().trim();
        String lin = jTextField3.getText().trim();
        int bN = Integer.parseInt(num);



        //CHANGE TRACK LIST !!+
        if(trackList != null) {
            Track temp2 = trackList;

            if(temp2.getBlockLine(bN,lin) != null)
                //Here need to go and print out block info
                jTextArea1.setText(temp2.getBlockLine(bN,lin).toString());
        }
        else
            jTextArea1.setText("Invalid Track or Block Number");

    }



    private void tickets(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        // Here need to go to NEW
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        refreshTickets();
    }

    private void loadTickets(){
        if(trackList != null){
            //Here need to populate TABLE
            DefaultTableModel table2 = (DefaultTableModel)jTable2.getModel();
            ArrayList<Station> station = trackList.getStations();
            table2.setRowCount(0);
            for(int i =0;i < station.size(); i++)
                table2.addRow(new Object[] {station.get(i).getLine(),station.get(i).getBlockNum(), station.get(i).getInfrastructure(), station.get(i).getTicketSales(), station.get(i).getThroughput()});
        }
    }
    public void refreshTickets() {
        timer = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadTickets();
            }
        });

        timer.setRepeats(true);
        // Aprox. 60 FPS
        timer.setDelay(17);
        timer.start();
    }

    /*Button for signals / signals / Beacons */

    private void signal(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        //Here update tables
        refreshSignals();
    }
    private void loadSignals(){

        if(trackList != null) {
            switches = (DefaultTableModel)jTable3.getModel();
            beacons = (DefaultTableModel)jTable5.getModel();
            mainInputs = (DefaultTableModel)jTable4.getModel();
            //switches.setRowCount(0);

            ArrayList<Switch> switchesList = trackList.getSwitches();
            ArrayList<Station> stationList = trackList.getStations();
            ArrayList<TrackElement> blockList = trackList.getBlocks();

            mainInputs.setRowCount(0);
            switches.setRowCount(0);
            beacons.setRowCount(0);
            for(int i=0; i<switchesList.size(); i++) {
                switches.addRow(new Object[] {switchesList.get(i).getLine(),switchesList.get(i).getBlockNum(), switchesList.get(i).getInfrastructure(),switchesList.get(i).getSwitchState()});

            }
            for(int i=0; i<stationList.size(); i++) {
                beacons.addRow(new Object[] {stationList.get(i).getLine(),stationList.get(i).getBlockNum(), stationList.get(i).getInfrastructure(),stationList.get(i).getBeacon()});

            }
            for(int i=0; i<blockList.size(); i++) {
                mainInputs.addRow(new Object[] {blockList.get(i).getLine(), blockList.get(i).getBlockNum(),blockList.get(i).getOccupied(),blockList.get(i).getAuthority(),blockList.get(i).dispCommandedSpeed()});

            }


        }
    }
    public void refreshSignals() {
        timer = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadSignals();
            }
        });

        timer.setRepeats(true);
        // Aprox. 60 FPS
        timer.setDelay(17);
        timer.start();
    }

    private void failures(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(true);
        jPanel7.setVisible(false);
        //add failure modes
        refreshFailures();
    }

    private void loadFailures(){
        if(trackList != null) {
            ArrayList<TrackElement> failureList = trackList.getFailures();
            DefaultTableModel failuresTable = (DefaultTableModel)jTable6.getModel();
            failuresTable.setRowCount(0);
            if(failureList != null) {
                for(int i=0; i<failureList.size(); i++) {
                    failuresTable.addRow(new Object[] {failureList.get(i).getLine(), failureList.get(i).getBlockNum(),failureList.get(i).getFailureStatus()});
                }
            }
        }
    }
    public void refreshFailures() {
        timer = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadFailures();
            }
        });

        timer.setRepeats(true);
        // Aprox. 60 FPS
        timer.setDelay(17);
        timer.start();
    }


    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(true);

    }

    /*UPDATING Track Temperature*/
    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        String temp = jTextField12.getText().trim();

        //need to call to change temp
        trackList.setEnvironmentalTemperature(Double.parseDouble(temp));

        //to repaint and update output
        viewTrack(evt);

    }

    /*Load Test Track File */
    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Track test = new Track();
        if(test.validFile("C:\\Users\\grhen\\OneDrive\\Documents\\Test.csv")){ // C:\Users\grhen\OneDrive\Documents\Test.csv"
            JOptionPane.showMessageDialog(null, "Loading Test Red Track");


            if(test.importTrack("C:\\Users\\grhen\\OneDrive\\Documents\\Test.csv")) {
                trackList = test;
                JOptionPane.showMessageDialog(null, "Track Successfully Loaded");
            }
            else
                JOptionPane.showMessageDialog(null, "ERROR: Track not loaded");
        }



    }

    /*Testing functionality of code */

    private void updateTestMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        //need to grab information from screen

        String blockNumT = BlockNumTest.getText().trim();
        String lineT =  lineTest.getText().trim();
        String occupiedT = occupiedTest.getText().trim();
        String authorityT = authorityTest.getText().trim();
        String speedT = speedTest.getText().trim();
        String switchT = switchTest.getText().trim();
        String passengerT = passengerTest.getText().trim();
        String failStatusT = failStatusTest.getText().trim();
        String lengthT = lengthTraveled.getText().trim();

        //Parsing info into different areas to test functionality
        int bN=0;
        int auth;
        int speed;
        int passenger;
        int switches;
        double LenT;
        TrackElement temp=null;

        if(trackList!=null) {
            if(!blockNumT.equals("Block Number")) {
                bN = Integer.parseInt(blockNumT);
                temp = trackList.getBlockLine(bN,lineT);
            }


            if(temp != null) {

                //changing occupied
                if(occupiedT.equals("1"))
                    temp.setOccupied(true);
                else if (occupiedT.equals("0"))
                    temp.setOccupied(false);

                //changing fail
                if(failStatusT.equals("0"))
                    trackList.setFailure(bN,lineT,0);
                else if (failStatusT.equals("1"))
                    trackList.setFailure(bN,lineT,1);
                else if(failStatusT.equals("2"))
                    trackList.setFailure(bN,lineT,2);
                else if (failStatusT.equals("3"))
                    trackList.setFailure(bN,lineT,3);

                if(!authorityT.equals("Authority")) {
                    auth = Integer.parseInt(authorityT);
                    temp.setAuthority(auth);
                }

                if(!speedT.equals("Speed")) {
                    speed = Integer.parseInt(speedT);
                    temp.setCommandedSpeed(speed);
                }

                if(!passengerT.equals("PassengerLeave")) {
                    passenger = Integer.parseInt(passengerT);
                    temp.setThroughput(passenger);
                }

                if(!switchT.equals("Change Switch")){
                    switches = Integer.parseInt(switchT);
                    temp.setSwitchState(switches);
                }

                if(!lengthT.equals("Length Traveled")){
                    LenT = Double.parseDouble(lengthT);
                    //  trackList.setTrainsLength(LenT);
                    //   JOptionPane.showMessageDialog(null, "NOW : " + trackList.getTrainsLength() + " AND " + trackList.getBlocksLength());
                }

            }
        }

    }



    private void jTestBlueMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Track test = new Track();
        if(test.validFile("C:\\Users\\grhen\\OneDrive\\Documents\\BlueLine.csv")){ // C:\Users\grhen\OneDrive\Documents\Test.csv"
            JOptionPane.showMessageDialog(null, "Loading Test Red Track");


            if(test.importTrack("C:\\Users\\grhen\\OneDrive\\Documents\\BlueLine.csv")) {
                trackList = test;
                JOptionPane.showMessageDialog(null, "Track Successfully Loaded");
            }
            else
                JOptionPane.showMessageDialog(null, "ERROR: Track not loaded");
        }
    }

    //ADDING ONLY GREEN LINE SHOWING
    private void greenTrackMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
       GREENDISP = 1;
    }

    private void viewGreenTrack(){
        if(trackList != null) {
            //Load in Green Track
            ArrayList<TrackElement> tempBlocks = trackList.getGreenLine();
            model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            for(int i=0; i<tempBlocks.size(); i++)
                model.addRow(new Object[] {tempBlocks.get(i).getBlockNum(),tempBlocks.get(i).getLine(),tempBlocks.get(i).getSection(), tempBlocks.get(i).getCurrentDirection(),tempBlocks.get(i).getDirectionString(),tempBlocks.get(i).getInfrastructure(), tempBlocks.get(i).getOccupied(), tempBlocks.get(i).getFailureStatus(), tempBlocks.get(i).getLength(), tempBlocks.get(i).getGrade(), tempBlocks.get(i).getSpeedLimit(), tempBlocks.get(i).getElevation(), tempBlocks.get(i).getCumulativeElevation() });
        }
    }
    public void refreshGreenTrack() {
        timer = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                viewGreenTrack();
            }
        });

        timer.setRepeats(true);
        // Aprox. 60 FPS
        timer.setDelay(17);
        timer.start();
    }
    /**
     * @param args the command line arguments
     */




   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackGUI(null).setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify
    private javax.swing.JTextField BlockNumTest;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Submit;
    private javax.swing.JTextPane TemperaturePane;
    private javax.swing.JTextField authorityTest;
    private javax.swing.JTextField failStatusTest;
    private javax.swing.JButton greenTrack;
    private javax.swing.JButton loadTrack;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton viewTrack;
    private javax.swing.JButton viewBlock;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton tickets;
    private javax.swing.JButton signal;
    private javax.swing.JButton failures;
    private javax.swing.JButton jButton9;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JButton jTestBlue;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField lengthTraveled;
    private javax.swing.JTextField lineTest;
    private javax.swing.JTextField occupiedTest;
    private javax.swing.JPanel panel_center;
    private javax.swing.JTextField passengerTest;
    private javax.swing.JTextField speedTest;
    private javax.swing.JTextField switchTest;
    private javax.swing.JButton updateTest;
    // End of variables declaration
}

